### PR TITLE
Convert to UTF-8 and add AsciiDoc sectioning

### PR DESCRIPTION
**Pull request by samwilson**
I'm not quite sure if I've done this correctly, but am sending this PR just to get feedback and see how things can be improved. :)

For instance, should the UTF-8 version actually be a separate file, or does one overwrite the existing `.txt` file?

And I removed the PG header... that's probably bad, but I wanted it to look nice on my ereader! :)

### CODE REVIEW

**Comment by sethwoodworth** [comment]
This looks good!  I pulled your branch, ran `asciidoctor` on `4302_utf8.txt`.  The html looks great!

Thank you for pointing out the ambiguities in the documentation about filename and PG headers.  Here are some things I'll fix/expand in the documentation:
- files can be `git mv`d from whatever their source file name 
  `git mv 4302.txt 4302.asciidoc`
- PG headers & footers can be moved to the `LICENSE` file in the root of the repo.

**Comment by sethwoodworth** [comment]
I'm going to go ahead and accept this and add this repo to the [active repos spreadsheet](https://github.com/gitenberg-dev/documentation/blob/master/activerepos.csv)

**Comment by samwilson** [comment]
That sounds good. I guess the metadata in the header will at some point be incorporated in whatever machine-readable system is going to be used for GITenberg metadata.

Thanks for looking at this!

I might rename the files, and do a bit more AsciiDoc formatting.

**Comment by sethwoodworth** [comment]
Please do!

The metadata can be used in a template that renders output formats of asciidoc books.  At some point we will start ensuring an asciidoc file has at least `X`, `Y`, & `Z` metadata filled out, but no one has decided which yet.

**Pull request merged**
