### PR TITLE
Punctuation and moving files and licence

### PR DESCRIPTION
**Pull request by samwilson**
I've moved the main source file to be called `4302.asciidoc`, moved the PG header and licence out of that file, and run the punctuation cleanup script.

Next I'll go through the resulting file manually and sort out formatting anomalies (i.e. as in #2).

I'm not sure about the `old` and `4302-h` directories. They seem redundant, and if they were removed would still be available in Git history; that seems a bit harsh though! However, future new revisions will be (well, already are) relying on Git's history, so perhaps that's okay?

### CODE REVIEW

**Comment by rdhyee-GITenberg** [comment]
@sethwoodworth @gitenjar  @samwilson Moving the Gutenberg front and back matter into LICENSE looks like a good solution. I have a concerns:  is there any requirement on Gutenberg books that we need to keep the license in the txt file? Anyone done a careful reading of http://www.gutenberg.org/wiki/Gutenberg:The_Project_Gutenberg_License?   I was thinking of keeping the license in the AsciiDoc source but marking it appropriately.

**Comment by sethwoodworth** [comment]
re: LICENSE

It is entirely possible to [include: license.adoc] into the final work, either at the beginning or end of the book.  This doesn't need to be decided right now.

The PG license is a distraction IMO.  We're not claiming the books are Project Gutenberg books, and they are otherwise released into the public domain.  I am fine keeping the license file far more hidden, and I would be willing to discuss removing/replacing it entirely.  For now, lets move to a separate file.

**Comment by sethwoodworth** [comment]
re: `old/` & `4302_h/`

These folders contain old releases of books and the hand-built html editions.  Lets keep them in the repos for now.

@gitenjar @rdhyee-GITenberg and I had a conversation this morning, and we are leaning towards keeping the original `.txt` edition of the file in the repo.  Sorry for the back and forth on this. I will update the documentation.

**Comment by samwilson** [comment]
I think @sethwoodworth is right about the license — it can be removed completely without harm. Actually, I seem to remember something once about PG requiring that it _either_ stays exactly as they arrange it, _or_ it's removed altogether. PG doesn't assert copyright over the works (of course) but they do over the other bits.

And yes, I agree about the old and html folders. Perhaps the solution is to move the `4302-h` and the original `.txt` into `old`? Then, they're all kept together, and away from the top-level (where there can just be a `4302.asciidoc.txt` maybe?).

**Comment by sethwoodworth** [comment]
For now, it can provide a backup source of html to build ebooks from.  All PG books that I have seen keep their html editions in the same sub-directory `-h`.  I am inclined to keep it as-is until a later cleanup phase of the project.

Lets move this conversation to the mailinglist!

**Comment by sethwoodworth** [comment]
Back to this PR discussion

In one of your commits you said "Clean up punctuation. Not manually checked yet."  Are you intending to do that, and should this PR wait on that?  Would you like help checking the unicode changes?

**Comment by samwilson** [comment]
Yep, I'm going to go through it manually and check things, but no merge this now if you're happy with how it stands. It'll take a week or so I think to read the book. :)

And yes, there's plenty of time later for cleanup!

I've joined the mailing list.

**Comment by sethwoodworth** [comment]
I'll let you review the unicode changes before I merge this.  If you want to cherrypick the other commits, I can merge them immediately.

**Comment by samwilson** [comment]
This is ready to merge. There might be few more typos, but I'll submit them in a future PR. The main stuff is done.

**Pull request merged**
